### ISSUE TITLE
Question about installation instructions

### ISSUE THREAD

**Issue by renkam** [salv-orlando/hdn#1]
Hi,
I am trying to install this just to se how it works by looking on the logs.
I can't find any useful information about how to install custom ML2 plugin. Could you please point me where to look for installation instructions?

**Comment by salv-orlando** [comment]
Hello!

I did unfortunately not update this repository in about 1.5 years, so it is very likely it won't work anymore as neutron's code base has been moving quite fast.

This is however not a ML2 driver, but a full plugin. You would need to specify the core plugin class path for the core_plugin configuration variable, and then add the l3 plugin class path to the service_plugins configuration variable.

I would love to find some time to do more work on this plugin, but unfortunately this is not possible at the moment. Also, it has no value at all beyond learning!

**Comment by renkam** [comment]
I am fully aware that all I can get from this is learning. I am trying to write my own driver and thought that HDN plugin would be a great starting point.
Thanks for the info, I'll give it another try.
